# Site settings
title:       ash.zi.vc
email:       a@zi.vc
author:      Ash Taylor
description: "I used to be a nice person. I still am, but I used to, too."
baseurl:     ""
url:         "http://ash.zi.vc"

# Google analytics
google_analytics: UA-61941979-1

# Optional features
animated:           true
show_related_posts: false
show_post_footers:  false

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname:

# Social icons
show_social_icons: true
github_username: zivc
stackoverflow_id:
twitter_username: zivcjs
google_plus_id:
linkedin_username: 60335448
bitcoin_url:
paypal_url:
flattr_button:

# Post sharing icons
show_sharing_icons: true
share_text: 'Clog up someones newsfeed with this post!'
# Change to 'true' to enable individual icons
share_facebook: true
share_twitter: true
share_googleplus: true
share_linkedin: true
share_digg: false
share_tumblr: false
share_reddit: true
share_stumbleupon: false

# Build settings
markdown:     redcarpet
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
paginate:     50
sass:
  compressed: true
